# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "DiFilippo lab"
title:              "DiFilippo lab at Johnson & Wales University"
description:        "This is a page for Nick DiFilippo lab, we perform research in robotics at Johnson & Wales University, Providence"

#URL
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html


# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "resources"
    href:           "/resources"


# Sass
sass:
  style:            :compressed



# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
